config/routes.rb
Blah::Application.routes.draw do

  match 'feedback' => 'contact#new'

  Blacklight.add_routes(self, :except => [:catalog, :solr_document])
  match 'catalogue/opensearch', :to => 'catalog#opensearch',  :as => 'opensearch_catalog'
  match 'catalogue/citation', :to => 'catalog#citation', :as => 'citation_catalog'
  match 'catalogue/sms', :to => 'catalog#sms',  :as => 'sms_catalog'
  match 'catalogue/endnote', :to => 'catalog#endnote', :as => 'endnote_catalog'
  match 'catalogue/facet/:id', :to => 'catalog#facet', :as => 'catalog_facet'
  match 'catalogue/range_limit', :to => 'catalog#range_limit', :as => 'catalog_range_limit'
  match 'catalogue', :to => 'catalog#index', :as => 'catalog_index'
  match 'catalogue/:id/librarian_view', :to => 'catalog#librarian_view', :as => 'librarian_view_catalog'

  resources :solr_document,  :path => 'catalogue', :controller => 'catalog', :only => [:show, :update] 
  resources :catalog, :path => 'catalogue', :controller => 'catalog', :only => [:show, :update]

  root :to => 'home#show'

  match 'items/:bib_no' => 'library_items#show'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
 
  match 'faq', :to => 'home#faq', :as => 'faq'
  match 'cookies', :to => 'home#cookies', :as => 'cookies'
  match 'home', :to => 'home#show', :as => 'home'

  devise_for :users

end

app/controllers/catalog_controller.rb
# -*- encoding : utf-8 -*-
require 'blacklight/catalog'

class CatalogController < ApplicationController
  include BlacklightGoogleAnalytics::ControllerExtraHead
  include Blacklight::Catalog

  #Manually add spam tool...
  before_filter :protect_from_spam, :only => :email  

  configure_blacklight do |config|
    ## Default parameters to send to solr for all search-like requests. See also SolrHelper#solr_search_params
    config.default_solr_params = { 
      :qt => 'search',
      :rows => 10 
    }

    ## Default parameters to send on single-document requests to Solr. These settings are the Blackligt defaults (see SolrHelper#solr_doc_params) or 
    ## parameters included in the Blacklight-jetty document requestHandler.
    #
    #config.default_document_solr_params = {
    #  :qt => 'document',
    #  ## These are hard-coded in the blacklight 'document' requestHandler
    #  # :fl => '*',
    #  # :rows => 1
    #  # :q => '{!raw f=id v=$id}' 
    #}

    # solr field configuration for search results/index views
    config.index.show_link = 'title_display'
    config.index.record_display_type = 'format'

    # solr field configuration for document/show views
    config.show.html_title = 'title_display'
    config.show.heading = 'title_display'
    config.show.display_type = 'format'

    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.    
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or 
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.  
    #
    # :show may be set to false if you don't want the facet to be drawn in the 
    # facet bar
    config.add_facet_field 'author_facet', :label => 'Author', :limit => 10
    config.add_facet_field 'format', :label => 'Format', :limit => 10
    config.add_facet_field 'library', :label => 'Library Location', :limit => 10
    config.add_facet_field 'pub_date', :label => 'Publication Year', :range => true
    config.add_facet_field 'subject_topic_facet', :label => 'Subject', :limit => 10
    config.add_facet_field 'language_facet', :label => 'Language', :limit => 10
    config.add_facet_field 'subject_geo_facet', :label => 'Region', :limit => 10
    config.add_facet_field 'subject_era_facet', :label => 'Era', :limit => 10

    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.default_solr_params[:'facet.field'] = config.facet_fields.keys
    #use this instead if you don't want to query facets marked :show=>false
    #config.default_solr_params[:'facet.field'] = config.facet_fields.select{ |k, v| v[:show] != false}.keys

    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display 
    config.add_index_field 'title_display', :label => 'Title:' 
    config.add_index_field 'title_vern_display', :label => 'Title:' 
    config.add_index_field 'author_t', :label => 'Author:' 
    config.add_index_field 'author_vern_display', :label => 'Author:' 
    config.add_index_field 'format', :label => 'Format:' 
    config.add_index_field 'language_facet', :label => 'Language:'
    config.add_index_field 'published_display', :label => 'Published:'
    config.add_index_field 'published_vern_display', :label => 'Published:'
    config.add_index_field 'lc_callnum_display', :label => 'Call number:'

  
    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display 
    config.add_show_field 'title_display', :label => 'Title:' 
    config.add_show_field 'title_vern_display', :label => 'Title:' 
    config.add_show_field 'subtitle_display', :label => 'Subtitle:' 
    config.add_show_field 'subtitle_vern_display', :label => 'Subtitle:' 
    config.add_show_field 'author_t', :label => 'Author:' 
    config.add_show_field 'author_vern_display', :label => 'Author:' 
    config.add_show_field 'format', :label => 'Format:' 
    config.add_show_field 'url_fulltext_display', :label => 'URL:'
    config.add_show_field 'url_suppl_display', :label => 'More Information:'
    config.add_show_field 'language_facet', :label => 'Language:'
    config.add_show_field 'published_display', :label => 'Published:'
    config.add_show_field 'published_vern_display', :label => 'Published:'
    config.add_show_field 'lc_callnum_display', :label => 'Call number:'
    config.add_show_field 'isbn_t', :label => 'ISBN:'

    # "fielded" search configuration. Used by pulldown among other places.
    # For supported keys in hash, see rdoc for Blacklight::SearchFields
    #
    # Search fields will inherit the :qt solr request handler from
    # config[:default_solr_parameters], OR can specify a different one
    # with a :qt key/value. Below examples inherit, except for subject
    # that specifies the same :qt as default for our own internal
    # testing purposes.
    #
    # The :key is what will be used to identify this BL search field internally,
    # as well as in URLs -- so changing it after deployment may break bookmarked
    # urls.  A display label will be automatically calculated from the :key,
    # or can be specified manually to be different. 

    # This one uses all the defaults set by the solr request handler. Which
    # solr request handler? The one set in config[:default_solr_parameters][:qt],
    # since we aren't specifying it otherwise. 
    
    config.add_search_field 'all_fields', :label => 'All Fields'
    

    # Now we see how to over-ride Solr request handler defaults, in this
    # case for a BL "search field", which is really a dismax aggregate
    # of Solr search fields. 
    
    config.add_search_field('title') do |field|
      # solr_parameters hash are sent to Solr as ordinary url query params. 
      field.solr_parameters = { :'spellcheck.dictionary' => 'title' }

      # :solr_local_parameters will be sent using Solr LocalParams
      # syntax, as eg {! qf=$title_qf }. This is neccesary to use
      # Solr parameter de-referencing like $title_qf.
      # See: http://wiki.apache.org/solr/LocalParams
      field.solr_local_parameters = { 
        :qf => '$title_qf',
        :pf => '$title_pf'
      }
    end
    
    config.add_search_field('author') do |field|
      field.solr_parameters = { :'spellcheck.dictionary' => 'author' }
      field.solr_local_parameters = { 
        :qf => '$author_qf',
        :pf => '$author_pf'
      }
    end
    
    # Specifying a :qt only to show it's possible, and so our internal automated
    # tests can test it. In this case it's the same as 
    # config[:default_solr_parameters][:qt], so isn't actually neccesary. 
    config.add_search_field('subject') do |field|
      field.solr_parameters = { :'spellcheck.dictionary' => 'subject' }
      field.qt = 'search'
      field.solr_local_parameters = { 
        :qf => '$subject_qf',
        :pf => '$subject_pf'
      }
    end

    # Specific classmark search - See solr schema.xml/solrconfig.xml for the specifics of the indexing
    config.add_search_field('classmark') do |field|
      field.solr_local_parameters = { 
        :qf => '$classmark_qf',
        :pf => '$classmark_pf'
      }
    end

    # "sort results by" select (pulldown)
    # label in pulldown is followed by the name of the SOLR field to sort by and
    # whether the sort is ascending or descending (it must be asc or desc
    # except in the relevancy case).
    config.add_sort_field 'score desc, pub_date desc, title_sort asc', :label => 'relevance'
    config.add_sort_field 'pub_date desc, title_sort asc', :label => 'year'
    config.add_sort_field 'author_sort asc, title_sort asc', :label => 'author'
    config.add_sort_field 'title_sort asc, pub_date desc', :label => 'title (ascending)'
    config.add_sort_field 'title_sort desc, pub_date desc', :label => 'title (descending)'

    # If there are more than this many search results, no spelling ("did you 
    # mean") suggestion is offered.
    config.spell_max = 5
  end

  # get single document from the solr index
  def show
      @response, @document = get_solr_response_for_doc_id   


      item_format = @document[:format].blank? ? 'Unknown' : @document[:format]
      #Create a library_item object
      @library_item = LibraryItem.new(@document.id, item_format)
      #load holdings records into the library_item object
      @library_item.load_holdings_records_collection 
      
      
      respond_to do |format|
        format.html {setup_next_and_previous_documents}

        # Add all dynamically added (such as by document extensions)
        # export formats.
        @document.export_formats.each_key do | format_name |
          # It's important that the argument to send be a symbol;
          # if it's a string, it makes Rails unhappy for unclear reasons. 
          format.send(format_name.to_sym) { render :text => @document.export_as(format_name), :layout => false }
        end
        
      end
    end

end 

app/views/catalog/_archival_material.html.erb
<div class="holdings">
  <div class="table-container">
    <table class="table availability-table">
      <thead>
        <tr>   
          <td colspan="3"><h5>Hull History Centre</h5><h5></h5></td>
        </tr>
      </thead>
      <tbody>
        <%= render_online_resources (@document) %>        
      </tbody>
		</table>
  </div>
</div>

app/views/catalog/_facet_pagination.html.erb
<span class="prev_next_links btn-group pull-left">
  <%= link_to_previous_page @pagination, raw(t('views.pagination.previous')), :params => params, :param_name => Blacklight::Solr::FacetPaginator.request_keys[:page], :class => 'btn' do %>
   <span class="disabled btn"><%= raw(t('views.pagination.previous')) %></span>
 <% end %>
  <%= link_to_next_page @pagination, raw(t('views.pagination.next')), :params => params, :param_name => Blacklight::Solr::FacetPaginator.request_keys[:page], :class => 'btn' do %>
   
   <span class="disabled btn"><%= raw(t('views.pagination.next')) %></span>
  <% end %>
</span>

<span class="sort_options btn-group pull-right">
  <% if @pagination.sort == 'index' -%>
    <span class="active az btn"><%= t('blacklight.search.facets.sort.index') %></span><%= link_to_unless(@pagination.sort == 'count', t('blacklight.search.facets.sort.count'), 
      @pagination.params_for_resort_url('count', params), :class => "sort_change numeric btn") %>
  <% elsif @pagination.sort == 'count' -%>
    <%=  link_to(t('blacklight.search.facets.sort.index'), @pagination.params_for_resort_url('index', params), 
      :class => "sort_change az btn") %><span class="active numeric btn"><%= t('blacklight.search.facets.sort.count') %></span>
  <% end -%>    
</span>

app/views/catalog/_index_archival_material.html.erb
<%# default partial to display solr document fields in catalog index view -%>
<%= display_field_within_element(document, 'id' , element='small') %>
<h4>Hull History Centre</h4>

app/views/catalog/_index_default.html.erb
<%= display_field_within_element(document, 'title_series_t' , element='h5') %>
<%= display_field_within_element(document, 'author_t' , element='h4') %>
<%= display_field_within_element(document, 'author_addl_t' , element='h5') %>
<%= display_field_within_element(document, 'pub_date_display' , element='small') %>
<%= display_field_within_element(document, 'edition_display' , element='small') %>

<%= jquery_holdings_display(document.id) %>
<%= display_full_text_links(document) %>

app/views/catalog/_marc_view.html.erb
<div id="marc_view">
  <% fields = @document.to_marc.find_all{|f| ('000'..'999') === f.tag }  %>
  <div class="field"><%= t('blacklight.search.librarian_view.leader', :leader => @document.to_marc.leader) %></div>
  <%- fields.each do |field| -%>
	<%- unless field.tag.to_s == "940" -%>
	  <div class="field">
	  	<div class="tag_ind">
	      <span class="tag">
	        <%= h(field.tag) %>
	  	  </span>
		  <%- if field.is_a?(MARC::ControlField) -%>
		    <span class="control_field_values">
		      <%= h(field.value) %>
		    </span>
		  <%- else -%>
		    <div class="ind1">
		      <%= !field.indicator1.blank? ? field.indicator1 : "&nbsp;&nbsp;".html_safe -%>
		    </div>
		    <div class="ind2">
		      <%= !field.indicator2.blank? ? field.indicator2 : "&nbsp;&nbsp;".html_safe -%>
		    </div>
		  </div>
		  <div class="subfields">
		    <%- field.each do |sub| -%>
			  <span class="sub_code"><%= h(sub.code) %>|</span> <%= h(sub.value) %>
			<%- end -%>
		  <%- end -%>
	    </div>
	  </div>
	<%- end-%>
  <%- end -%>
</div>

app/views/catalog/_per_page_widget.html.erb
<% if show_sort_and_per_page? and !blacklight_config.per_page.blank? %>
<div id="per_page-dropdown" class="dropdown pull-right  hidden-phone">
  <span class="hide-text"><%= t('blacklight.search.per_page.title') %></span>
  <ul class="css-dropdown">
    <li class="btn btn-small square-corners">
      <%= link_to(t(:'blacklight.search.per_page.button_label', :count => current_per_page), "#") %> <span class="caret"></span>
      <ul>
        <%- blacklight_config.per_page.each do |count| %>
          <li><%= link_to(t(:'blacklight.search.per_page.label', :count => count).html_safe, url_for(params_for_search.merge(:per_page => count))) %></li>
        <%- end -%>
      </ul>
    </li>
  </ul>
</div>
<% end %>

app/views/catalog/_results_pagination.html.erb
<% if paginate_params(@response).num_pages > 1 %>
 <div class="row record-padding">
  <div class="span16 hidden-phone">
    <div class="pagination">
      <%= paginate_rsolr_response @response, :outer_window => 2, :theme => 'blacklight' %>
    </div>
  </div>
 </div>
<% end %>

app/views/catalog/_search_form.html.erb
<div class="subnav navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container container-fluid-fix">
      <div class="row-fluid">
          <div class="subnav-position">

            <%= form_tag catalog_index_path, :method => :get, :class => 'form-inline form-search form-sub-search'  do %>

            <div class="input-prepend input-append">

              <%= search_as_hidden_fields(:omit_keys => [:q, :search_field, :qt, :page]).html_safe %> 

              <% unless search_fields.empty? %>
                <%= select_tag(:search_field, options_for_select(search_fields, h(params[:search_field])), :title => t('blacklight.search.form.search_field.title'), :class=>"search-field square-corners input-medium") %>
              <% end %>

              <%= text_field_tag :q, params[:q], :class =>  "q input-xlarge search-query square-corners", :placeholder => 'Search the catalogue...' %>

              <button class="btn square-corners" name="button" type="submit"><i class="icon-search icon hidden-phone"></i> Search</button>
 
            </div>
            <span class="hidden-phone">
              <span class="vertical-divider hidden-phone"></span>
              <%= link_to 'Advanced search', params.merge(:controller=>"advanced", :action=>"index") , :class=>"advanced_search row-spacer"%>
            </span>

            <div class="visible-phone">
              <hr style="margin-bottom: 10px;"/>
              <span>
                <%= link_to 'Advanced search', params.merge(:controller=>"advanced", :action=>"index") , :class=>"advanced_search row-spacer"%>
              </span>              
            </div>  
                     
          </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/catalog/_show_availability.html.erb
<div class="container-gutter">
  <h3>Availability</h3> 
</div>
<div id="availability-nav" class="sidebar-nav well square-corners">
  <% if !@library_item.nil? && @library_item.inter_library_loan? %>
      <p>Available through <%= link_to "Inter-Library Loan", inter_library_loan_url %></p>
  <% else %>
    <% unless @document["format"] == "Electronic resource" || @document["format"]  == "Archival material" %>
      <p><%= render_millennium_record_link "Find loan period information here" %></p>
    <% end %>
  <% end %>


  <% #This will be set to display:block using javascript if no holdings/online resources are present -See holdings_record.js -%>
  <p id="no-holdings" class="hide"><%= t('blah.item.holdings.no_holdings_information') %></p>
  <%= render_holdings_html_partial(@library_item) unless @library_item.nil? %>
<% if @document["format"] == "E-Journal" || @document["format"] == "E-Book" || @document["format"] == "E-Thesis" || @document["format"] == "Electronic resource" %>
<%= render_online_resources_partial(@document) %>
<% end %>  
<% if @document["format"] == "Archival material" %>
<%= render_archival_material_partial(@document) %>
<% end %>
</div>

app/views/catalog/_show_electronic_resource.html.erb
<div class="row-fluid">
  <div id="document-header" class="span16">
    <%= render_document_heading(:h2).html_safe %> 
  </div>
</div>
<div class="row-fluid">
     <div class="span12">
        <h3>Record</h3>
        <dl class="dl-vertical-left  dl-invert">
          <%= display_field(document, 'description_display', 'Description', 'description', {:contains_encoded_html => true}) %>
          <%#= display_field(document, 'subject_t', 'Subject', 'subject') %>
          <%= display_field_search_link(document, 'subject_t', 'Subject', 'subject', 'subject-link', 'subject') %>
          <%= display_field(document, 'format', 'Format', 'format') %>
          <%= display_field(document, 'lc_callnum_display', 'Call number', 'call') %>
          <%= display_field(document, 'coverage_display', 'Coverage', 'coverage') %>
        </dl>
        <h3>Access information</h3>
        <dl class="dl-vertical-left  dl-invert">
          <%= display_field(document, 'access_info_display', 'Access', 'access-info', {:contains_encoded_html => true}) %>
          <%= display_field(document, 'auth_users_display', 'Authorised users', 'auth-users') %>
          <%= display_field(document, 'published_vern_display', 'Published', 'pub') %>
          <%= display_field(document, 'isbn_t', 'ISBN', 'isbn') %>
          <%= display_field(document, 'terms_display', 'Terms of use', 'terms', {:contains_encoded_html => true}) %>
          <%= display_field(document, 'additional_info_display', 'Additional information', 'add-info', {:contains_encoded_html => true}) %>
        </dl>
     </div>
</div>

app/views/catalog/_show_tools.html.erb
<%-
  # Compare with render_document_functions_partial helper, and
  # _document_functions partial. BL actually has two groups
  # of document-related tools. "document functions" by default
  # contains Bookmark/Folder functionality shown on both results and
  # item view. While "document tools" contains external export type
  # functions by default only on detail.

  #Added Bootstrap class well and 'hidden-phone' for the tools-bar 
-%>

  <!-- desktop -->
  <div id="tools-nav">
    <ul class="nav nav-pills visible-desktop">
      <% if (@document.respond_to?(:export_as_mla_citation_txt) || @document.respond_to?(:export_as_apa_citation_txt)) %>
        <li class="cite">
         <%= link_to t('blacklight.tools.cite'), citation_catalog_path(:id => @document), {:id => 'citeLink', :name => 'citation', :class => 'lightboxLink btn btn-small square-corners'} %></i>
        </li>
      <% end %>
      <% if @document.export_formats.keys.include?( :refworks_marc_txt ) %>
        <li class="refworks">
        <%= link_to t('blacklight.tools.refworks'), refworks_export_url(:id => @document), {:class => 'btn btn-small square-corners', :target => '_blank'}  %>        
        </li>
     <% end %>
     <% if @document.export_formats.keys.include?( :endnote ) %>
      <li class="endnote">
      <%= link_to t('blacklight.tools.endnote'), catalog_path(@document, :format => 'endnote'), {:class => 'btn btn-small square-corners'} %>
      </li>
    <% end %>
    <% if @document.respond_to?( :to_email_text ) %>
      <li class="email">
      <a class="btn btn-small square-corners" href="mailto:?subject=You have been sent a link for The University of Hull Library Catalogue: <%= @document.get('title_display') %>&body=You have been sent a link to an item at The University of Hull Library Catalogue: %0D%0A%0D%0ATitle: <%= @document.get('title_display') %>, %0D%0AAuthor: <%= @document.get('author_addl_t') %>, %0D%0ALanguage: <%= @document.get('language_facet') %>, %0D%0AURL: http://libsearch.hull.ac.uk/catalogue/<%= @document.get('id') %>">   Email</a>
      </li>
    <%- end -%>
    
    <% if @document.respond_to?(:to_marc) %>
      <li class="librarian_view">
        <%= link_to t('blacklight.tools.librarian_view'), librarian_view_catalog_path(@document), {:id => 'librarianLink', :name => 'librarian_view', :class => 'lightboxLink btn btn-small square-corners'} %>
      </li>
    <% end %>

     <% unless @library_item.nil? %>
      <% if @library_item.requestable? %>
        <li class="hold_item">
          <%= render_request_library_item_link(@library_item, "btn btn-small square-corners") %>
        </li>
      <% end %>

      
    <% end %>
    <%= render :partial => 'qr_code' %>
    <%= render :partial => 'addthis_tool' %>
    </ul>


    <!-- tablet -->
    <div class="visible-tablet">
      <div class="btn-group">
        <button class="btn btn-large dropdown-toggle square-corners" data-toggle="dropdown">Tools <span class="caret"></span></button>
          <ul class="dropdown-menu square-corners">
            <% if (@document.respond_to?(:export_as_mla_citation_txt) || @document.respond_to?(:export_as_apa_citation_txt)) %>
              <li class="cite">
                <%= link_to t('blacklight.tools.cite'), citation_catalog_path(:id => @document), {:id => 'citeLink', :name => 'citation'} %></i>
              </li>
            <% end %>
            <% if @document.export_formats.keys.include?( :refworks_marc_txt ) %>
              <li class="refworks">
              <%= link_to t('blacklight.tools.refworks'), refworks_export_url(:id => @document), { :target => '_blank'}  %>        
              </li>
            <% end %>
            <% if @document.export_formats.keys.include?( :endnote ) %>
              <li class="endnote">
              <%= link_to t('blacklight.tools.endnote'), catalog_path(@document, :format => 'endnote') %>
              </li>
            <% end %>
            <% if @document.respond_to?( :to_email_text ) %>
              <li class="email">
                    <a class="square-corners" href="mailto:?subject=You have been sent a link for The University of Hull Library Catalogue: <%= @document.get('title_display') %>&body=You have been sent a link to an item at The University of Hull Library Catalogue: %0D%0A%0D%0ATitle: <%= @document.get('title_display') %>, %0D%0AAuthor: <%= @document.get('author_addl_t') %>, %0D%0ALanguage: <%= @document.get('language_facet') %>, %0D%0AURL: http://libsearch.hull.ac.uk/catalogue/<%= @document.get('id') %>">   Email</a>
              </li>
            <%- end -%>
            <% if @document.respond_to?(:to_marc) %>
              <li class="librarian_view">
                <%= link_to t('blacklight.tools.librarian_view'), librarian_view_catalog_path(@document), {:id => 'librarianLink', :name => 'librarian_view', :class => 'lightboxLink square-corners'} %>
              </li>
            <% end %>

           <% unless @library_item.nil? %>
            <% if @library_item.requestable? %>
              <li class="hold_item">
                <%= render_request_library_item_link(@library_item, "") %>
              </li>
            <% end %>

            
          <% end %>


          <li class="qr_code">
            <%= link_to "QR Code", "#myModal", {:id => 'qr-link', :name => 'qr-view', "data-toggle" => "modal" } %>
          </li> 

          <li class="addthis">
            <%= link_to "Share", "http://www.addthis.com/bookmark.php?v=20", {:class => 'addthis_button', :style => 'text-decoration:none;'} %>      
          </li>

          </ul>
        </div>
    </div>

    <!-- mobile-->
    <ul class="nav nav-pills nav-stacked visible-phone">
      <% if (@document.respond_to?(:export_as_mla_citation_txt) || @document.respond_to?(:export_as_apa_citation_txt)) %>
        <li class="cite">
         <%= link_to t('blacklight.tools.cite'), citation_catalog_path(:id => @document), {:id => 'citeLink', :name => 'citation', :class => 'lightboxLink btn btn-small square-corners'} %></i>
        </li>
      <% end %>
      <% if @document.export_formats.keys.include?( :refworks_marc_txt ) %>
        <li class="refworks">
        <%= link_to t('blacklight.tools.refworks'), refworks_export_url(:id => @document), {:class => 'btn btn-small square-corners', :target => '_blank'}  %>        
        </li>
     <% end %>
     <% if @document.export_formats.keys.include?( :endnote ) %>
      <li class="endnote">
      <%= link_to t('blacklight.tools.endnote'), catalog_path(@document, :format => 'endnote'), {:class => 'btn btn-small square-corners'} %>
      </li>
    <% end %>
    <% if @document.respond_to?( :to_email_text ) %>
      <li class="email">
            <a class="btn btn-small square-corners" href="mailto:?subject=You have been sent a link for The University of Hull Library Catalogue: <%= @document.get('title_display') %>&body=You have been sent a link to an item at The University of Hull Library Catalogue: %0D%0A%0D%0ATitle: <%= @document.get('title_display') %>, %0D%0AAuthor: <%= @document.get('author_addl_t') %>, %0D%0ALanguage: <%= @document.get('language_facet') %>, %0D%0AURL: http://libsearch.hull.ac.uk/catalogue/<%= @document.get('id') %>">   Email</a>
      </li>
    <%- end -%>     
    <% if @document.respond_to?(:to_marc) %>
      <li class="librarian_view">
        <%= link_to t('blacklight.tools.librarian_view'), librarian_view_catalog_path(@document), {:id => 'librarianLink', :name => 'librarian_view', :class => 'lightboxLink btn btn-small square-corners'} %>
      </li>
    <% end %>
   <% unless @library_item.nil? %>
      <% if @library_item.requestable? %>
        <li class="hold_item">
          <%= render_request_library_item_link(@library_item, "btn btn-small square-corners") %>
        </li>
      <% end %>
<% end %>
    <%= render :partial => 'qr_code' %>
    <%= render :partial => 'addthis_tool' %> 
    
    </ul>

  </div>

app/views/catalog/_sort_and_per_page.html.erb
<div id="sortAndPerPage">

   <div class="page_links">
     <h3>Results <small><%= render :partial => "paginate_compact" %></small>
     </h3>
   </div>
    <%= render :partial => 'sort_widget' %>

    <%= render :partial => 'per_page_widget' %>

</div>

app/views/catalog/_sort_widget.html.erb
<% if show_sort_and_per_page? and !blacklight_config.sort_fields.blank? %>
<div id="sort-dropdown" class="dropdown pull-right hidden-phone">
  <ul class="css-dropdown">
    <li class="btn btn-small square-corners">
      <%= link_to(t('blacklight.search.sort.label', :field =>current_sort_field.label), "#") %> <span class="caret"></span>
      <ul>
        <%- blacklight_config.sort_fields.each do |sort_key, field| %>
          <li><%= link_to(field.label, url_for(params_for_search.merge(:sort => sort_key))) %></li>
        <%- end -%>
      </ul>
    </li>
  </ul>
</div>
<% end %>

app/views/catalog/librarian_view.html.erb
<div class="modal-header">
  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
  <h3><%= t('blacklight.search.librarian_view.title') %></h3>
</div>
<%- if @document.respond_to?(:to_marc) -%>
  <%= render "marc_view" %>
<%- else %>
      No MARC data found.
<%- end -%>