config/routes.rb
Blah::Application.routes.draw do

  match 'feedback' => 'contact#new'

  Blacklight.add_routes(self, :except => [:catalog, :solr_document])
  match 'catalogue/opensearch', :to => 'catalog#opensearch',  :as => 'opensearch_catalog'
  match 'catalogue/citation', :to => 'catalog#citation', :as => 'citation_catalog'
  match 'catalogue/sms', :to => 'catalog#sms',  :as => 'sms_catalog'
  match 'catalogue/endnote', :to => 'catalog#endnote', :as => 'endnote_catalog'
  match 'catalogue/facet/:id', :to => 'catalog#facet', :as => 'catalog_facet'
  match 'catalogue/range_limit', :to => 'catalog#range_limit', :as => 'catalog_range_limit'
  match 'catalogue', :to => 'catalog#index', :as => 'catalog_index'
  match 'catalogue/:id/librarian_view', :to => 'catalog#librarian_view', :as => 'librarian_view_catalog'

  resources :solr_document,  :path => 'catalogue', :controller => 'catalog', :only => [:show, :update] 
  resources :catalog, :path => 'catalogue', :controller => 'catalog', :only => [:show, :update]

  root :to => 'home#show'

  match 'items/:bib_no' => 'library_items#show'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
 
  match 'faq', :to => 'home#faq', :as => 'faq'
  match 'cookies', :to => 'home#cookies', :as => 'cookies'
  match 'home', :to => 'home#show', :as => 'home'

  devise_for :users

end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

 def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])

    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Your message has been sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

end

app/helpers/contact_helper.rb
module ContactHelper
end

app/views/contact/new.html.erb
<div class="page-gutter">
  <h1><%= t('blah.contact_form.title') %></h1>
  <div class="well">
    <p>
      <%= t('blah.contact_form.description') %>
    </p>
  </div>
  <%= form_for @message, :url => contact_path, :html => { :honeypot => true } do |form| %>
    <fieldset class="fields">
      <h3>Your Details</h3>
      <div class="field">
        <%= form.label :name, t('blah.contact_form.name'), :class=> 'form-label' %>
        <%= form.text_field :name, :class=> 'input-xxlarge', :placeholder=> 'Please enter your name...' %>
      </div>
      <div class="field">
        <%= form.label :email, t('blah.contact_form.email'), :class=> 'form-label' %>
        <%= form.text_field :email, :class=> 'input-xxlarge', :placeholder=> 'Please enter your email address...' %>
      </div>
      <h3>Your Message</h3>
      <div class="field">
        <%= form.label :subject, t('blah.contact_form.subject'), :class=> 'form-label' %>
        <%= form.text_field :subject, :class=> 'input-xxlarge',  :placeholder=> 'Please enter a subject title...' %>
      </div>
      
      <div class="field">
        <%= form.label :body, t('blah.contact_form.body'), :class=> 'form-label' %>
        <%= form.text_area :body, :class=> 'input-xxlarge', :placeholder=> 'Please enter your feedback...' %>
      </div>
    </fieldset>
    
    <hr/>

    <fieldset class="actions">
      <%= form.submit "Send feedback", :class=> 'btn square-corners' %>
    </fieldset>
  <% end %>
</div>