config/routes.rb
Blah::Application.routes.draw do

  match 'feedback' => 'contact#new'

  Blacklight.add_routes(self, :except => [:catalog, :solr_document])
  match 'catalogue/opensearch', :to => 'catalog#opensearch',  :as => 'opensearch_catalog'
  match 'catalogue/citation', :to => 'catalog#citation', :as => 'citation_catalog'
  match 'catalogue/sms', :to => 'catalog#sms',  :as => 'sms_catalog'
  match 'catalogue/endnote', :to => 'catalog#endnote', :as => 'endnote_catalog'
  match 'catalogue/facet/:id', :to => 'catalog#facet', :as => 'catalog_facet'
  match 'catalogue/range_limit', :to => 'catalog#range_limit', :as => 'catalog_range_limit'
  match 'catalogue', :to => 'catalog#index', :as => 'catalog_index'
  match 'catalogue/:id/librarian_view', :to => 'catalog#librarian_view', :as => 'librarian_view_catalog'

  resources :solr_document,  :path => 'catalogue', :controller => 'catalog', :only => [:show, :update] 
  resources :catalog, :path => 'catalogue', :controller => 'catalog', :only => [:show, :update]

  root :to => 'home#show'

  match 'items/:bib_no' => 'library_items#show'

  match 'contact' => 'contact#new', :as => 'contact', :via => :get
  match 'contact' => 'contact#create', :as => 'contact', :via => :post
 
  match 'faq', :to => 'home#faq', :as => 'faq'
  match 'cookies', :to => 'home#cookies', :as => 'cookies'
  match 'home', :to => 'home#show', :as => 'home'

  devise_for :users

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blah</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/blacklight.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta name="description" content="Search the library's holdings for books, e-books and other electronic resources, images, journals and other periodicals, plus more.">
    <meta name="author" content="The University of Hull">
    <meta name="keywords" content="Library, Catalogue, search, holdings, books, e-books, electronic resources, images, journals, periodicals, Hull, University, blacklight, libsearch">
    <!-- Mobile viewport optimization h5bp.com/ad -->
    <meta name="HandheldFriendly" content="True">
    <% #meta tags for customising view on Apple devices -%>
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />

    <!-- Mobile IE allows us to activate ClearType technology for smoothing fonts for easy reading -->
    <!--[if IEMobile]>
      <meta http-equiv="cleartype" content="on">
    <![endif]-->
 
    <%= render :partial => 'shared/head_favicon_links' %>
    <%= render :partial => 'shared/head_add_to_home' %>

    <title><%= h(@page_title || application_name) %></title>
    <link href="<%= opensearch_catalog_path(:format => 'xml', :only_path => false) %>" title="<%= application_name%>" type="application/opensearchdescription+xml" rel="search"/>    
  
    <%= stylesheet_link_tag "application" %>
    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag 'stay_standalone' %> 

    <%= csrf_meta_tags %>
    <%= raw(render_head_content) %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]--> 

    <!--[if lt IE 9]>
    <style type="text/css">
      #feedback {
        display: none;
      }
    </style>
    <![endif]-->

  </head>
  <% onload_text = "$('input#q').focus();" if params[:q].to_s.empty? and params[:f].to_s.empty? and params[:id].nil? %>
  <body onload="<%= onload_text %>" class="<%= render_body_class %>">
    <%= render :partial => 'shared/header_navbar' %>

    <div id="ajax-modal" class="modal hide fade" tabindex="-1"></div>

    <div class="page-wrapper">
     
      <% # Use a different background-container div for the home page %>
      <% if (current_page?(controller: 'home', action: 'show')) %>
        <div id="background-container" class="container">
      <% else %>
        <div id="background-container-form" class="container">
      <% end %>

  
          <% if !(current_page?(controller: 'home', action: 'show')) %>
            <div id="form-container">
          <% end %>

            <!-- Top bar 
            <div id="search-found" class="row hidden-phone">
              <%#= topbar_items.join('').html_safe %>
            </div>
            -->
            <!-- /Top bar -->
            <div class="row">
              <% if !(current_page?(controller: 'home', action: 'show')) %>
                <div class="desktop-top-spacer visible-desktop"></div>
                <div class="tablet-top-spacer visible-tablet"></div>
              <% end %>
              <%= render :partial=>'/flash_msg' %>
            </div>
            <%= yield %>

          <% if !(current_page?(controller: 'home', action: 'show')) %>
            </div>
          <% end %>

      </div>
        <%= render :partial => 'shared/feedback_element' %>
    </div>
    <%= render :partial => 'shared/footer' %>
  </body>
</html>